import { ClerkProvider, UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { CetExtraLogo } from "@/components/icons/CetExtraLogo";
import { Cog6ToothIcon } from "@heroicons/react/24/outline";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <div
        className={`${geistSans.variable} ${geistMono.variable} mx-auto flex h-screen w-full flex-col px-6 antialiased`}
      >
        <div className="relative flex items-center">
          <CetExtraLogo className="h-16 w-16 lg:invisible" />
          <span className="absolute left-1/2 -translate-x-1/2 transform text-2xl lg:text-6xl">
            Bienvenue John Doe
          </span>
          <div className="ml-auto flex gap-1">
            <div className="h-7 w-7 rounded-full">
              <Cog6ToothIcon className="h-full w-full" />
            </div>
            <div className="h-7 w-7">
              <UserButton />
            </div>
          </div>
        </div>
        <div className="my-auto flex max-h-[80vh] flex-1 bg-main-gradient p-6">
          {children}
        </div>
      </div>
    </ClerkProvider>
  );
}
